### ISSUE TITLE
Running examples without install

### ISSUE THREAD

**Issue by tgarc** [posborne/cmsis-svd#20]
Nice little project!

Can I run the examples directly from the development directory / without installing? I tried

``git/cmsis-svd/python$ python -m cmsis_svd.examples.show_k20_json``

But it can't find the file:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tdos/git/cmsis-svd/python/cmsis_svd/examples/show_k20_json.py", line 19, in <module>
    parser = SVDParser.for_packaged_svd('Freescale', 'MK20D7.xml')
  File "cmsis_svd/parser.py", line 80, in for_packaged_svd
    return cls.for_xml_file(pkg_resources.resource_filename("cmsis_svd", resource))
  File "cmsis_svd/parser.py", line 70, in for_xml_file
    return cls(ET.parse(path))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: 'cmsis_svd/data/Freescale/MK20D7.xml'

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tdos/git/cmsis-svd/python/cmsis_svd/examples/show_k20_json.py", line 19, in <module>
    parser = SVDParser.for_packaged_svd('Freescale', 'MK20D7.xml')
  File "cmsis_svd/parser.py", line 80, in for_packaged_svd
    return cls.for_xml_file(pkg_resources.resource_filename("cmsis_svd", resource))
  File "cmsis_svd/parser.py", line 70, in for_xml_file
    return cls(ET.parse(path))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: 'cmsis_svd/data/Freescale/MK20D7.xml'
```

**Comment by posborne** [comment]
Looks like there were two issues:

1. When not installed, there is no data directory under cmsis_svd so the pkg_resources lookup fails
2. Files now end in .svd instead of .xml

Although it is not fully portable, I am adding a symlink to the git repo to the data directory.  Windows users will just need to use released versions of build the symlink/copy themselves.
